FINMAN/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('backend.urls', namespace='backend')),
]

backend/urls.py
from django.urls import path
from . import views

app_name = 'backend'

urlpatterns = [

    path('', views.user_login, name='login'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('account/', views.account, name='account'),
    path('account/add', views.add_account, name='add_account'),
    path('account/<int:account_id>', views.account_details, name='account_details'),
    path('transaction/', views.transaction, name='transaction'),
    path('transaction/add', views.add_transaction, name='add_transaction'),
    path('user/<str:username>', views.profile, name='profile'),

]

backend/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from django.contrib.auth.models import User
import uuid

class Account(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=128, default='Cash')
    description = models.CharField(max_length=512, null=True)
    balance = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    currency = models.CharField(max_length=4, default='BDT')

    def __str__(self):
        return self.name

class Transaction(models.Model):
    id = models.CharField(max_length=128, primary_key=True, blank=True, unique=True, default=uuid.uuid4)
    user = models.CharField(max_length=128, default='Anonymous')
    timestamp = models.DateTimeField(timezone.now())
    account = models.CharField(max_length=128, default='Cash')
    type = models.CharField(max_length=8, default='debit')
    amount = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    remark = models.CharField(max_length=256)

    def __str__(self):
        return self.id

class Extended(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    total_debit = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    total_credit = models.DecimalField(max_digits=20, decimal_places=2, default=0)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Extended.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.extended.save()

backend/forms.py
from django import forms
from django.utils import timezone

class AddAccount(forms.Form):
    name = forms.CharField(max_length=128)
    balance = forms.DecimalField()
    currency = forms.CharField(max_length=4)
    description = forms.CharField(max_length=512)

class AddTransaction(forms.Form):
    timestamp = forms.DateField(widget=forms.SelectDateWidget, initial=timezone.now())
    accountID = forms.IntegerField()
    user = forms.CharField(max_length=128)
    type = forms.CharField(max_length=8)
    amount = forms.DecimalField()
    remark = forms.CharField(max_length=256)

backend/views.py
from django.contrib.auth.decorators import login_required
from .models import Transaction, Account
from .forms import AddAccount, AddTransaction
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm


def user_login(request):
    context = {}
    next = request.GET.get('next')
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            if next:
                return redirect(next)
            else:
                messages.success(request, "You have successfully logged in!")
                return redirect('backend:account')
        else:
            messages.error(request, "Provide valid credentials.")
            return render(request, 'auth/login.html')

    else:
        return render(request, 'auth/login.html', context)


def user_register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('backend:profile')
    else:
        form = UserCreationForm()
    return render(request, 'auth/register.html', {'form': form})


def user_logout(request):
    messages.success(request, "You have been logged out!")
    logout(request)
    return redirect('auth:login')

def profile(request, username):
    profile = User.objects.get(username=username)
    all_transaction_list = Transaction.objects.all()
    user_transaction = []
    for transaction in all_transaction_list:
        if transaction.user == profile.username:
            user_transaction.append(transaction)

    if user_transaction is None:
        messages.error(request, "No transaction exists in the system.")
        return render(request, 'user/profile.html', {'profile': profile, 'user_transaction': None})
    else:
        return render(request, 'user/profile.html', {'profile': profile, 'user_transaction': user_transaction})

def add_transaction(request):
    all_account_list = Account.objects.all()
    
    if request.method == 'POST':

        form = AddTransaction(request.POST)
        if form.is_valid():
            account = Account.objects.get(id=form.cleaned_data['accountID'])
            usernm = request.user.username
            user = User.objects.get(username=usernm)
            print(account)
            print(user)
            transaction = Transaction(
                timestamp=form.cleaned_data['timestamp'],
                account=account.name,
                user=form.cleaned_data['user'],
                type=form.cleaned_data['type'],
                amount=form.cleaned_data['amount'],
                remark=form.cleaned_data['remark'],
            )
            if form.cleaned_data['type'] == 'Debit':
                account.balance -= form.cleaned_data['amount']
                user.extended.total_debit += form.cleaned_data['amount']
            elif form.cleaned_data['type'] == 'Credit':
                account.balance += form.cleaned_data['amount']
                user.extended.total_credit += form.cleaned_data['amount']
            account.save()
            transaction.save()
            user.save()
            messages.success(request, "Successfully added a new transaction!")
            return redirect('backend:transaction')
        else:
            messages.warning(request, "Couldn't add new transaction")
            return redirect('backend:transaction')

    else:
        form = AddTransaction()
        return render(request, 'transaction/add_transaction.html', {'form': form, 'account_list': all_account_list})

def add_account(request):
    if request.method == 'POST':

        form = AddAccount(request.POST)
        if form.is_valid():
            account = Account(
                name = form.cleaned_data['name'],
                balance = form.cleaned_data['balance'],
                currency = form.cleaned_data['currency'],
                description = form.cleaned_data['description'],
            )
            account.save()
            messages.success(request, "Successfully added a new account!")
            return redirect('backend:account')
        else:
            messages.warning(request, "Couldn't add new account")
            return redirect('backend:account')

    else:
        form = AddAccount()
        return render(request, 'account/add_account.html', {'form': form})

def account(request):
    all_account_list = Account.objects.all()

    if all_account_list is None:
        messages.error(request, "No account exists in the system.")
        return render(request, 'account/account.html', {'account_list': None})
    else:
        return render(request, 'account/account.html', {'account_list': all_account_list})

def transaction(request):
    all_transaction_list = Transaction.objects.all()
    USER = User.objects.all()

    if all_transaction_list is None:
        messages.error(request, "No transaction exists in the system.")
        return render(request, 'transaction/transaction.html', {'transaction_list': None, 'users': USER})
    else:
        return render(request, 'transaction/transaction.html', {'transaction_list': all_transaction_list, 'users': USER})

def account_details(request, account_id):
    acc = Account.objects.get(id=account_id)
    accnm = acc.name
    transaction_list = Transaction.objects.filter(account__icontains=accnm)
    USER = User.objects.all()

    if transaction_list is None:
        messages.error(request, "No transaction exists in the system.")
        return render(request, 'account/account_details.html', {'account': acc, 'account_transaction': None, 'users': USER})
    else:
        return render(request, 'account/account_details.html', {'account': acc, 'account_transaction': transaction_list, 'users': USER})

backend/templates/transaction/add_transaction.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block body %}

    <h1 style="width: 100%; margin: 20px; text-align: center">New Transaction</h1>

    <hr>

    <form action="{% url 'backend:add_transaction' %}" method="POST">
        <div class="form-group">
            {% csrf_token %}
            <div class="form-group">
                <label for="timestamp">TimeStamp</label>
                {% render_field form.timestamp class+="form-control"%}
            </div>
            <input type='hidden' name="user" value={{ request.user.username }}>
            <div class="form-group">
                <label for="accountID">Account</label>
                <select class="form-control" title="account" name="accountID">
                    {% for acc in account_list %}
                        <option value={{ acc.id }}>{{ acc }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="type">Type</label>
                <select class="form-control" title="type" name="type">
                        <option>Credit</option>
                        <option>Debit</option>
                </select>
            </div>
            <div class="form-group">
                <label for="amount">Amount</label>
                {% render_field form.amount class+="form-control"%}
            </div>
            <div class="form-group">
                <label for="remark">Remark</label>
                {% render_field form.remark class+="form-control"%}
            </div>
            

            <div class="form-group" style="display: flex; justify-content: space-around; margin: 40px">
                <a href="{% url 'backend:transaction' %}" type="button" class="btn btn-secondary">
                    Back
                </a>
                <input type="submit" class="btn btn-primary" value="Submit">
            </div>
        </div>
    </form>

{% endblock %}

{% block styles %}

    a, a:hover {
        color: #be1e2d;
    }

{% endblock %}

{% block head %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
{% endblock %}

backend/templates/transaction/transaction.html
{% extends 'base.html' %}

{% block body %}

    <h1 style="width: 100%; margin: 20px; text-align: center">Transaction</h1>

    <div style="display: flex; justify-content: space-between; flex-wrap: wrap">

            <a type="button" class="btn col-xl-2 col-lg-2 col-md-4 col-sm-5 col-5" style="margin: 10px; background-color: #373839; font-weight: bold" href="{% url 'backend:add_transaction' %}">
                Add Transaction
            </a>
    </div>

    <div style="margin-top: 40px">
    {% if transaction_list %}
        <table class="table table-hover table-bordered">
            <tbody>
                <tr style="text-align: center; background-color: #373839">
                    <th scope="col">ID</th>
                    <th scope="col">TimeStamp</th>
                    <th scope="col">User</th>
                    <th scope="col">Account</th>
                    <th scope="col">Type</th>
                    <th scope="col">Amount</th>
                    <th scope="col">Remark</th>
                </tr>
                {% for transaction in transaction_list %}
                    <tr>
                    <th>{{ transaction.id }}</th>
                    <td>{{ transaction.timestamp }}</td>
                    <td>{% for user in users %}
                            {% if transaction.user == user.username %}
                            <a href="{% url 'backend:profile' user.username %}">{{ transaction.user }}</a>
                            {% else %}
                            {{ transaction.user }}
                            {% endif %}
                        {% endfor %}
                    </td>
                    <td>{{ transaction.account }}</td>
                    <td>{{ transaction.type }}</td>
                    <td>{{ transaction.amount }}</td>
                    <td>{{ transaction.remark }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p style="width: 100%; margin: 20px; text-align: center">No transaction present in the database</p>
    {% endif %}
    </div>

{% endblock %}

{% block styles %}

    a, a:hover {
        color: #be1e2d;
    }

{% endblock %}

{% block head %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
{% endblock %}